/**
 * Игровые константы. Все размеры — в "дизайн-пикселях" относительно
 * базовой высоты/ширины 1000px; конкретные значения считает Metrics.
 */
export const gameConfig = {
  commands: { play: '!play' },
  texts: {
    startTitle: 'SHOOTING WORD',
    startSubtitle: 'Введи !play чтобы играть',
    gameOverTitle: 'ЧАТ, ВЫ ПРОИГРАЛИ!',
    gameOverSubtitle: 'Введи !play чтобы играть',
    scoreLabel: 'SCORE:',
    waveLabel: 'WAVE:',
    livesLabel: 'LIVES:',
    finalScoreLabel: 'Final Score:',
    armorLabel: 'ARMOR',
    bossLabel: 'BOSS',
    bossIncoming: 'BOSS INCOMING',
  },
  game: {
    startLives: 10,
    startWave: 1,
    startScore: 0,
    enemiesPerWaveBase: 5,
    enemiesPerWaveInc: 1,
    waveInterval: 900,
    heavyEnemyChanceBase: 0.25,
    heavyEnemyChancePerWave: 0.02,
    scoreSimple: 10,
    scoreHeavy: 50,
    scoreBoss: 200,
    bossEveryNthWave: 10,
    bossLayers: 3,
    bossWordsPerLayer: 3,
    gameOverDelay: 10000,
  },
  speed: {
    slowEnemyCrossTimeStart: 240,
    slowEnemyCrossTimeCap: 30,
    slowEnemyCrossTimeCapWave: 50,
    fastEnemyCrossTimeStart: 120,
    fastEnemyCrossTimeCap: 15,
    fastEnemyCrossTimeCapWave: 50,
    bossCrossTime: 60,
    projectileCrossTime: 0.43,
    gridSpeed: 0.5,
  },
  visual: {
    gridSize: 80,
    enemyPaddingX: 60,
    enemyAlienOffset: 16,
    armorBarPad: 20,
    armorBarFont: 20,
    missTargetPadX: 60,
    missTargetPadY: 100,
    inputAreaHeight: 105,
    removeZone: 60,
    playerY: 32,
    playerRadius: 16,
    playerGlow: 30,
    enemySimpleHeight: 30,
    enemyHeavyHeight: 42,
    enemySimpleFont: 28,
    enemyHeavyFont: 30,
    enemyArmorBarHeight: 6,
    enemyArmorBarOffset: 11,
    enemyArmorLabelOffset: 15,
    enemyGlow: 10,
    enemyFlashGlow: 50,
    enemyLineWidth: 3,
    projectileGlow: 30,
    projectileHitRadius: 30,
    projectileMissRadius: 30,
    projectileFont: 28,
    projectileCircleRadius: 30,
    shakeHit: 8,
    shakeMiss: 6,
    shakeDamage: 16,
    particleVel: 12,
    particleSizeMin: 4,
    particleSizeMax: 10,
    particleGlow: 16,
    trailSizeBase: 4,
    trailSizeInc: 1,
    trailGlow: 20,
    shooterOffset: 50,
    wavePauseFont: 36,
  },
  ratio: {
    missTargetYRange: 0.5,
    projectileTrailLength: 8,
    projectileTrailDecay: 0.15,
    projectileTrailAlpha: 0.6,
    projectileCircleAlpha: 0.5,
    enemyPulseRate: 0.05,
    enemyAlphaBase: 1.0,
    enemyAlphaRange: 0.0,
    enemyGlowPulse: 5,
    particleDecayBase: 0.02,
    particleDecayRange: 0.03,
    particleDamping: 0.98,
    bossFontSizeFactor: 1.2,
    bossHeightFactor: 1.5,
    bossWordGap: 24,
  },
  counts: {
    projectileTrailLength: 8,
    particleHit: 15,
    particleMiss: 20,
    particleDestroySimple: 15,
    particleDestroyHeavy: 30,
    particleArmorBreak: 15,
    flashDuration: 10,
    shakeHitDuration: 6,
    shakeMissDuration: 5,
    shakeDamageDuration: 10,
    wavePauseFrames: 120,
  },
  timing: {
    inputShootDelay: 150,
    glitchDuration: 300,
  },
  colors: {
    primary: '#00ff41',
    primaryDim: '#00cc33',
    primaryGlow: 'rgba(0,255,65,0.2)',
    primaryGrid: 'rgba(0,255,65,0.08)',
    heavy: '#ffaa00',
    heavyDim: '#cc8800',
    boss: '#ff4444',
    bossDim: '#cc2222',
    miss: '#ff0044',
    white: '#ffffff',
    red: '#ff0000',
    armorBarBg: 'rgba(255,0,0,0.3)',
    armorBarFill: '#ffaa00',
    enemyFill: '#0a0a0a',
    playerBase: 'rgba(0,255,65,0.15)',
    scanline: 'rgba(0,255,65,0.03)',
  },
  font: '"Courier New", monospace',
  intro: {
    fontSize: 44,
    textYR: 0.35,
    subtitleYOffset: 60,
    fadeInFrames: 40,
    shot1Frame: 45,
    shot2Frame: 70,
    shot3Frame: 95,
    shotSpeed: 0.045,
    particleCountPerHit: 18,
    slideStartFrame: 122,
    slideDuration: 20,
    totalFrames: 180,
    startDelay: 300,
    glow: 50,
    trailGlow: 20,
    projectileGlow: 30,
    projectileRadius: 8,
    trailRect: 8,
    trailMax: 10,
    trailDecay: 0.12,
    trailAlpha: 0.5,
    subtitleFont: 32,
    subtitleGlow: 20,
  },
} as const

export type GameConfig = typeof gameConfig
